<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities=[
            ["id" => 1, "province_id" => 21, "city_name" => "Kabupaten Aceh Barat"],
            ["id" => 2, "province_id" => 21, "city_name" => "Kabupaten Aceh Barat Daya"],
            ["id" => 3, "province_id" => 21, "city_name" => "Kabupaten Aceh Besar"],
            ["id" => 4, "province_id" => 21, "city_name" => "Kabupaten Aceh Jaya"],
            ["id" => 5, "province_id" => 21, "city_name" => "Kabupaten Aceh Selatan"],
            ["id" => 6, "province_id" => 21, "city_name" => "Kabupaten Aceh Singkil"],
            ["id" => 7, "province_id" => 21, "city_name" => "Kabupaten Aceh Tamiang"],
            ["id" => 8, "province_id" => 21, "city_name" => "Kabupaten Aceh Tengah"],
            ["id" => 9, "province_id" => 21, "city_name" => "Kabupaten Aceh Tenggara"],
            ["id" => 10, "province_id" => 21, "city_name" => "Kabupaten Aceh Timur"],
            ["id" => 11, "province_id" => 21, "city_name" => "Kabupaten Aceh Utara"],
            ["id" => 12, "province_id" => 32, "city_name" => "Kabupaten Agam"],
            ["id" => 13, "province_id" => 23, "city_name" => "Kabupaten Alor"],
            ["id" => 14, "province_id" => 19, "city_name" => "Kota Ambon"],
            ["id" => 15, "province_id" => 34, "city_name" => "Kabupaten Asahan"],
            ["id" => 16, "province_id" => 24, "city_name" => "Kabupaten Asmat"],
            ["id" => 17, "province_id" => 1, "city_name" => "Kabupaten Badung"],
            ["id" => 18, "province_id" => 13, "city_name" => "Kabupaten Balangan"],
            ["id" => 19, "province_id" => 15, "city_name" => "Kota Balikpapan"],
            ["id" => 20, "province_id" => 21, "city_name" => "Kota Banda Aceh"],
            ["id" => 21, "province_id" => 18, "city_name" => "Kota Bandar Lampung"],
            ["id" => 22, "province_id" => 9, "city_name" => "Kabupaten Bandung"],
            ["id" => 23, "province_id" => 9, "city_name" => "Kota Bandung"],
            ["id" => 24, "province_id" => 9, "city_name" => "Kabupaten Bandung Barat"],
            ["id" => 25, "province_id" => 29, "city_name" => "Kabupaten Banggai"],
            ["id" => 26, "province_id" => 29, "city_name" => "Kabupaten Banggai Kepulauan"],
            ["id" => 27, "province_id" => 2, "city_name" => "Kabupaten Bangka"],
            ["id" => 28, "province_id" => 2, "city_name" => "Kabupaten Bangka Barat"],
            ["id" => 29, "province_id" => 2, "city_name" => "Kabupaten Bangka Selatan"],
            ["id" => 30, "province_id" => 2, "city_name" => "Kabupaten Bangka Tengah"],
            ["id" => 31, "province_id" => 11, "city_name" => "Kabupaten Bangkalan"],
            ["id" => 32, "province_id" => 1, "city_name" => "Kabupaten Bangli"],
            ["id" => 33, "province_id" => 13, "city_name" => "Kabupaten Banjar"],
            ["id" => 34, "province_id" => 9, "city_name" => "Kota Banjar"],
            ["id" => 35, "province_id" => 13, "city_name" => "Kota Banjarbaru"],
            ["id" => 36, "province_id" => 13, "city_name" => "Kota Banjarmasin"],
            ["id" => 37, "province_id" => 10, "city_name" => "Kabupaten Banjarnegara"],
            ["id" => 38, "province_id" => 28, "city_name" => "Kabupaten Bantaeng"],
            ["id" => 39, "province_id" => 5, "city_name" => "Kabupaten Bantul"],
            ["id" => 40, "province_id" => 33, "city_name" => "Kabupaten Banyuasin"],
            ["id" => 41, "province_id" => 10, "city_name" => "Kabupaten Banyumas"],
            ["id" => 42, "province_id" => 11, "city_name" => "Kabupaten Banyuwangi"],
            ["id" => 43, "province_id" => 13, "city_name" => "Kabupaten Barito Kuala"],
            ["id" => 44, "province_id" => 14, "city_name" => "Kabupaten Barito Selatan"],
            ["id" => 45, "province_id" => 14, "city_name" => "Kabupaten Barito Timur"],
            ["id" => 46, "province_id" => 14, "city_name" => "Kabupaten Barito Utara"],
            ["id" => 47, "province_id" => 28, "city_name" => "Kabupaten Barru"],
            ["id" => 48, "province_id" => 17, "city_name" => "Kota Batam"],
            ["id" => 49, "province_id" => 10, "city_name" => "Kabupaten Batang"],
            ["id" => 50, "province_id" => 8, "city_name" => "Kabupaten Batang Hari"],
            ["id" => 51, "province_id" => 11, "city_name" => "Kota Batu"],
            ["id" => 52, "province_id" => 34, "city_name" => "Kabupaten Batu Bara"],
            ["id" => 53, "province_id" => 30, "city_name" => "Kota Bau-Bau"],
            ["id" => 54, "province_id" => 9, "city_name" => "Kabupaten Bekasi"],
            ["id" => 55, "province_id" => 9, "city_name" => "Kota Bekasi"],
            ["id" => 56, "province_id" => 2, "city_name" => "Kabupaten Belitung"],
            ["id" => 57, "province_id" => 2, "city_name" => "Kabupaten Belitung Timur"],
            ["id" => 58, "province_id" => 23, "city_name" => "Kabupaten Belu"],
            ["id" => 59, "province_id" => 21, "city_name" => "Kabupaten Bener Meriah"],
            ["id" => 60, "province_id" => 26, "city_name" => "Kabupaten Bengkalis"],
            ["id" => 61, "province_id" => 12, "city_name" => "Kabupaten Bengkayang"],
            ["id" => 62, "province_id" => 4, "city_name" => "Kota Bengkulu"],
            ["id" => 63, "province_id" => 4, "city_name" => "Kabupaten Bengkulu Selatan"],
            ["id" => 64, "province_id" => 4, "city_name" => "Kabupaten Bengkulu Tengah"],
            ["id" => 65, "province_id" => 4, "city_name" => "Kabupaten Bengkulu Utara"],
            ["id" => 66, "province_id" => 15, "city_name" => "Kabupaten Berau"],
            ["id" => 67, "province_id" => 24, "city_name" => "Kabupaten Biak Numfor"],
            ["id" => 68, "province_id" => 22, "city_name" => "Kabupaten Bima"],
            ["id" => 69, "province_id" => 22, "city_name" => "Kota Bima"],
            ["id" => 70, "province_id" => 34, "city_name" => "Kota Binjai"],
            ["id" => 71, "province_id" => 17, "city_name" => "Kabupaten Bintan"],
            ["id" => 72, "province_id" => 21, "city_name" => "Kabupaten Bireuen"],
            ["id" => 73, "province_id" => 31, "city_name" => "Kota Bitung"],
            ["id" => 74, "province_id" => 11, "city_name" => "Kabupaten Blitar"],
            ["id" => 75, "province_id" => 11, "city_name" => "Kota Blitar"],
            ["id" => 76, "province_id" => 10, "city_name" => "Kabupaten Blora"],
            ["id" => 77, "province_id" => 7, "city_name" => "Kabupaten Boalemo"],
            ["id" => 78, "province_id" => 9, "city_name" => "Kabupaten Bogor"],
            ["id" => 79, "province_id" => 9, "city_name" => "Kota Bogor"],
            ["id" => 80, "province_id" => 11, "city_name" => "Kabupaten Bojonegoro"],
            ["id" => 81, "province_id" => 31, "city_name" => "Kabupaten Bolaang Mongondow (Bolmong)"],
            ["id" => 82, "province_id" => 31, "city_name" => "Kabupaten Bolaang Mongondow Selatan"],
            ["id" => 83, "province_id" => 31, "city_name" => "Kabupaten Bolaang Mongondow Timur"],
            ["id" => 84, "province_id" => 31, "city_name" => "Kabupaten Bolaang Mongondow Utara"],
            ["id" => 85, "province_id" => 30, "city_name" => "Kabupaten Bombana"],
            ["id" => 86, "province_id" => 11, "city_name" => "Kabupaten Bondowoso"],
            ["id" => 87, "province_id" => 28, "city_name" => "Kabupaten Bone"],
            ["id" => 88, "province_id" => 7, "city_name" => "Kabupaten Bone Bolango"],
            ["id" => 89, "province_id" => 15, "city_name" => "Kota Bontang"],
            ["id" => 90, "province_id" => 24, "city_name" => "Kabupaten Boven Digoel"],
            ["id" => 91, "province_id" => 10, "city_name" => "Kabupaten Boyolali"],
            ["id" => 92, "province_id" => 10, "city_name" => "Kabupaten Brebes"],
            ["id" => 93, "province_id" => 32, "city_name" => "Kota Bukittinggi"],
            ["id" => 94, "province_id" => 1, "city_name" => "Kabupaten Buleleng"],
            ["id" => 95, "province_id" => 28, "city_name" => "Kabupaten Bulukumba"],
            ["id" => 96, "province_id" => 16, "city_name" => "Kabupaten Bulungan (Bulongan)"],
            ["id" => 97, "province_id" => 8, "city_name" => "Kabupaten Bungo"],
            ["id" => 98, "province_id" => 29, "city_name" => "Kabupaten Buol"],
            ["id" => 99, "province_id" => 19, "city_name" => "Kabupaten Buru"],
            ["id" => 100, "province_id" => 19, "city_name" => "Kabupaten Buru Selatan"],
            ["id" => 101, "province_id" => 30, "city_name" => "Kabupaten Buton"],
            ["id" => 102, "province_id" => 30, "city_name" => "Kabupaten Buton Utara"],
            ["id" => 103, "province_id" => 9, "city_name" => "Kabupaten Ciamis"],
            ["id" => 104, "province_id" => 9, "city_name" => "Kabupaten Cianjur"],
            ["id" => 105, "province_id" => 10, "city_name" => "Kabupaten Cilacap"],
            ["id" => 106, "province_id" => 3, "city_name" => "Kota Cilegon"],
            ["id" => 107, "province_id" => 9, "city_name" => "Kota Cimahi"],
            ["id" => 108, "province_id" => 9, "city_name" => "Kabupaten Cirebon"],
            ["id" => 109, "province_id" => 9, "city_name" => "Kota Cirebon"],
            ["id" => 110, "province_id" => 34, "city_name" => "Kabupaten Dairi"],
            ["id" => 111, "province_id" => 24, "city_name" => "Kabupaten Deiyai (Deliyai)"],
            ["id" => 112, "province_id" => 34, "city_name" => "Kabupaten Deli Serdang"],
            ["id" => 113, "province_id" => 10, "city_name" => "Kabupaten Demak"],
            ["id" => 114, "province_id" => 1, "city_name" => "Kota Denpasar"],
            ["id" => 115, "province_id" => 9, "city_name" => "Kota Depok"],
            ["id" => 116, "province_id" => 32, "city_name" => "Kabupaten Dharmasraya"],
            ["id" => 117, "province_id" => 24, "city_name" => "Kabupaten Dogiyai"],
            ["id" => 118, "province_id" => 22, "city_name" => "Kabupaten Dompu"],
            ["id" => 119, "province_id" => 29, "city_name" => "Kabupaten Donggala"],
            ["id" => 120, "province_id" => 26, "city_name" => "Kota Dumai"],
            ["id" => 121, "province_id" => 33, "city_name" => "Kabupaten Empat Lawang"],
            ["id" => 122, "province_id" => 23, "city_name" => "Kabupaten Ende"],
            ["id" => 123, "province_id" => 28, "city_name" => "Kabupaten Enrekang"],
            ["id" => 124, "province_id" => 25, "city_name" => "Kabupaten Fakfak"],
            ["id" => 125, "province_id" => 23, "city_name" => "Kabupaten Flores Timur"],
            ["id" => 126, "province_id" => 9, "city_name" => "Kabupaten Garut"],
            ["id" => 127, "province_id" => 21, "city_name" => "Kabupaten Gayo Lues"],
            ["id" => 128, "province_id" => 1, "city_name" => "Kabupaten Gianyar"],
            ["id" => 129, "province_id" => 7, "city_name" => "Kabupaten Gorontalo"],
            ["id" => 130, "province_id" => 7, "city_name" => "Kota Gorontalo"],
            ["id" => 131, "province_id" => 7, "city_name" => "Kabupaten Gorontalo Utara"],
            ["id" => 132, "province_id" => 28, "city_name" => "Kabupaten Gowa"],
            ["id" => 133, "province_id" => 11, "city_name" => "Kabupaten Gresik"],
            ["id" => 134, "province_id" => 10, "city_name" => "Kabupaten Grobogan"],
            ["id" => 135, "province_id" => 5, "city_name" => "Kabupaten Gunung Kidul"],
            ["id" => 136, "province_id" => 14, "city_name" => "Kabupaten Gunung Mas"],
            ["id" => 137, "province_id" => 34, "city_name" => "Kota Gunungsitoli"],
            ["id" => 138, "province_id" => 20, "city_name" => "Kabupaten Halmahera Barat"],
            ["id" => 139, "province_id" => 20, "city_name" => "Kabupaten Halmahera Selatan"],
            ["id" => 140, "province_id" => 20, "city_name" => "Kabupaten Halmahera Tengah"],
            ["id" => 141, "province_id" => 20, "city_name" => "Kabupaten Halmahera Timur"],
            ["id" => 142, "province_id" => 20, "city_name" => "Kabupaten Halmahera Utara"],
            ["id" => 143, "province_id" => 13, "city_name" => "Kabupaten Hulu Sungai Selatan"],
            ["id" => 144, "province_id" => 13, "city_name" => "Kabupaten Hulu Sungai Tengah"],
            ["id" => 145, "province_id" => 13, "city_name" => "Kabupaten Hulu Sungai Utara"],
            ["id" => 146, "province_id" => 34, "city_name" => "Kabupaten Humbang Hasundutan"],
            ["id" => 147, "province_id" => 26, "city_name" => "Kabupaten Indragiri Hilir"],
            ["id" => 148, "province_id" => 26, "city_name" => "Kabupaten Indragiri Hulu"],
            ["id" => 149, "province_id" => 9, "city_name" => "Kabupaten Indramayu"],
            ["id" => 150, "province_id" => 24, "city_name" => "Kabupaten Intan Jaya"],
            ["id" => 151, "province_id" => 6, "city_name" => "Kota Jakarta Barat"],
            ["id" => 152, "province_id" => 6, "city_name" => "Kota Jakarta Pusat"],
            ["id" => 153, "province_id" => 6, "city_name" => "Kota Jakarta Selatan"],
            ["id" => 154, "province_id" => 6, "city_name" => "Kota Jakarta Timur"],
            ["id" => 155, "province_id" => 6, "city_name" => "Kota Jakarta Utara"],
            ["id" => 156, "province_id" => 8, "city_name" => "Kota Jambi"],
            ["id" => 157, "province_id" => 24, "city_name" => "Kabupaten Jayapura"],
            ["id" => 158, "province_id" => 24, "city_name" => "Kota Jayapura"],
            ["id" => 159, "province_id" => 24, "city_name" => "Kabupaten Jayawijaya"],
            ["id" => 160, "province_id" => 11, "city_name" => "Kabupaten Jember"],
            ["id" => 161, "province_id" => 1, "city_name" => "Kabupaten Jembrana"],
            ["id" => 162, "province_id" => 28, "city_name" => "Kabupaten Jeneponto"],
            ["id" => 163, "province_id" => 10, "city_name" => "Kabupaten Jepara"],
            ["id" => 164, "province_id" => 11, "city_name" => "Kabupaten Jombang"],
            ["id" => 165, "province_id" => 25, "city_name" => "Kabupaten Kaimana"],
            ["id" => 166, "province_id" => 26, "city_name" => "Kabupaten Kampar"],
            ["id" => 167, "province_id" => 14, "city_name" => "Kabupaten Kapuas"],
            ["id" => 168, "province_id" => 12, "city_name" => "Kabupaten Kapuas Hulu"],
            ["id" => 169, "province_id" => 10, "city_name" => "Kabupaten Karanganyar"],
            ["id" => 170, "province_id" => 1, "city_name" => "Kabupaten Karangasem"],
            ["id" => 171, "province_id" => 9, "city_name" => "Kabupaten Karawang"],
            ["id" => 172, "province_id" => 17, "city_name" => "Kabupaten Karimun"],
            ["id" => 173, "province_id" => 34, "city_name" => "Kabupaten Karo"],
            ["id" => 174, "province_id" => 14, "city_name" => "Kabupaten Katingan"],
            ["id" => 175, "province_id" => 4, "city_name" => "Kabupaten Kaur"],
            ["id" => 176, "province_id" => 12, "city_name" => "Kabupaten Kayong Utara"],
            ["id" => 177, "province_id" => 10, "city_name" => "Kabupaten Kebumen"],
            ["id" => 178, "province_id" => 11, "city_name" => "Kabupaten Kediri"],
            ["id" => 179, "province_id" => 11, "city_name" => "Kota Kediri"],
            ["id" => 180, "province_id" => 24, "city_name" => "Kabupaten Keerom"],
            ["id" => 181, "province_id" => 10, "city_name" => "Kabupaten Kendal"],
            ["id" => 182, "province_id" => 30, "city_name" => "Kota Kendari"],
            ["id" => 183, "province_id" => 4, "city_name" => "Kabupaten Kepahiang"],
            ["id" => 184, "province_id" => 17, "city_name" => "Kabupaten Kepulauan Anambas"],
            ["id" => 185, "province_id" => 19, "city_name" => "Kabupaten Kepulauan Aru"],
            ["id" => 186, "province_id" => 32, "city_name" => "Kabupaten Kepulauan Mentawai"],
            ["id" => 187, "province_id" => 26, "city_name" => "Kabupaten Kepulauan Meranti"],
            ["id" => 188, "province_id" => 31, "city_name" => "Kabupaten Kepulauan Sangihe"],
            ["id" => 189, "province_id" => 6, "city_name" => "Kabupaten Kepulauan Seribu"],
            ["id" => 190, "province_id" => 31, "city_name" => "Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)"],
            ["id" => 191, "province_id" => 20, "city_name" => "Kabupaten Kepulauan Sula"],
            ["id" => 192, "province_id" => 31, "city_name" => "Kabupaten Kepulauan Talaud"],
            ["id" => 193, "province_id" => 24, "city_name" => "Kabupaten Kepulauan Yapen (Yapen Waropen)"],
            ["id" => 194, "province_id" => 8, "city_name" => "Kabupaten Kerinci"],
            ["id" => 195, "province_id" => 12, "city_name" => "Kabupaten Ketapang"],
            ["id" => 196, "province_id" => 10, "city_name" => "Kabupaten Klaten"],
            ["id" => 197, "province_id" => 1, "city_name" => "Kabupaten Klungkung"],
            ["id" => 198, "province_id" => 30, "city_name" => "Kabupaten Kolaka"],
            ["id" => 199, "province_id" => 30, "city_name" => "Kabupaten Kolaka Utara"],
            ["id" => 200, "province_id" => 30, "city_name" => "Kabupaten Konawe"],
            ["id" => 201, "province_id" => 30, "city_name" => "Kabupaten Konawe Selatan"],
            ["id" => 202, "province_id" => 30, "city_name" => "Kabupaten Konawe Utara"],
            ["id" => 203, "province_id" => 13, "city_name" => "Kabupaten Kotabaru"],
            ["id" => 204, "province_id" => 31, "city_name" => "Kota Kotamobagu"],
            ["id" => 205, "province_id" => 14, "city_name" => "Kabupaten Kotawaringin Barat"],
            ["id" => 206, "province_id" => 14, "city_name" => "Kabupaten Kotawaringin Timur"],
            ["id" => 207, "province_id" => 26, "city_name" => "Kabupaten Kuantan Singingi"],
            ["id" => 208, "province_id" => 12, "city_name" => "Kabupaten Kubu Raya"],
            ["id" => 209, "province_id" => 10, "city_name" => "Kabupaten Kudus"],
            ["id" => 210, "province_id" => 5, "city_name" => "Kabupaten Kulon Progo"],
            ["id" => 211, "province_id" => 9, "city_name" => "Kabupaten Kuningan"],
            ["id" => 212, "province_id" => 23, "city_name" => "Kabupaten Kupang"],
            ["id" => 213, "province_id" => 23, "city_name" => "Kota Kupang"],
            ["id" => 214, "province_id" => 15, "city_name" => "Kabupaten Kutai Barat"],
            ["id" => 215, "province_id" => 15, "city_name" => "Kabupaten Kutai Kartanegara"],
            ["id" => 216, "province_id" => 15, "city_name" => "Kabupaten Kutai Timur"],
            ["id" => 217, "province_id" => 34, "city_name" => "Kabupaten Labuhan Batu"],
            ["id" => 218, "province_id" => 34, "city_name" => "Kabupaten Labuhan Batu Selatan"],
            ["id" => 219, "province_id" => 34, "city_name" => "Kabupaten Labuhan Batu Utara"],
            ["id" => 220, "province_id" => 33, "city_name" => "Kabupaten Lahat"],
            ["id" => 221, "province_id" => 14, "city_name" => "Kabupaten Lamandau"],
            ["id" => 222, "province_id" => 11, "city_name" => "Kabupaten Lamongan"],
            ["id" => 223, "province_id" => 18, "city_name" => "Kabupaten Lampung Barat"],
            ["id" => 224, "province_id" => 18, "city_name" => "Kabupaten Lampung Selatan"],
            ["id" => 225, "province_id" => 18, "city_name" => "Kabupaten Lampung Tengah"],
            ["id" => 226, "province_id" => 18, "city_name" => "Kabupaten Lampung Timur"],
            ["id" => 227, "province_id" => 18, "city_name" => "Kabupaten Lampung Utara"],
            ["id" => 228, "province_id" => 12, "city_name" => "Kabupaten Landak"],
            ["id" => 229, "province_id" => 34, "city_name" => "Kabupaten Langkat"],
            ["id" => 230, "province_id" => 21, "city_name" => "Kota Langsa"],
            ["id" => 231, "province_id" => 24, "city_name" => "Kabupaten Lanny Jaya"],
            ["id" => 232, "province_id" => 3, "city_name" => "Kabupaten Lebak"],
            ["id" => 233, "province_id" => 4, "city_name" => "Kabupaten Lebong"],
            ["id" => 234, "province_id" => 23, "city_name" => "Kabupaten Lembata"],
            ["id" => 235, "province_id" => 21, "city_name" => "Kota Lhokseumawe"],
            ["id" => 236, "province_id" => 32, "city_name" => "Kabupaten Lima Puluh Koto/Kota"],
            ["id" => 237, "province_id" => 17, "city_name" => "Kabupaten Lingga"],
            ["id" => 238, "province_id" => 22, "city_name" => "Kabupaten Lombok Barat"],
            ["id" => 239, "province_id" => 22, "city_name" => "Kabupaten Lombok Tengah"],
            ["id" => 240, "province_id" => 22, "city_name" => "Kabupaten Lombok Timur"],
            ["id" => 241, "province_id" => 22, "city_name" => "Kabupaten Lombok Utara"],
            ["id" => 242, "province_id" => 33, "city_name" => "Kota Lubuk Linggau"],
            ["id" => 243, "province_id" => 11, "city_name" => "Kabupaten Lumajang"],
            ["id" => 244, "province_id" => 28, "city_name" => "Kabupaten Luwu"],
            ["id" => 245, "province_id" => 28, "city_name" => "Kabupaten Luwu Timur"],
            ["id" => 246, "province_id" => 28, "city_name" => "Kabupaten Luwu Utara"],
            ["id" => 247, "province_id" => 11, "city_name" => "Kabupaten Madiun"],
            ["id" => 248, "province_id" => 11, "city_name" => "Kota Madiun"],
            ["id" => 249, "province_id" => 10, "city_name" => "Kabupaten Magelang"],
            ["id" => 250, "province_id" => 10, "city_name" => "Kota Magelang"],
            ["id" => 251, "province_id" => 11, "city_name" => "Kabupaten Magetan"],
            ["id" => 252, "province_id" => 9, "city_name" => "Kabupaten Majalengka"],
            ["id" => 253, "province_id" => 27, "city_name" => "Kabupaten Majene"],
            ["id" => 254, "province_id" => 28, "city_name" => "Kota Makassar"],
            ["id" => 255, "province_id" => 11, "city_name" => "Kabupaten Malang"],
            ["id" => 256, "province_id" => 11, "city_name" => "Kota Malang"],
            ["id" => 257, "province_id" => 16, "city_name" => "Kabupaten Malinau"],
            ["id" => 258, "province_id" => 19, "city_name" => "Kabupaten Maluku Barat Daya"],
            ["id" => 259, "province_id" => 19, "city_name" => "Kabupaten Maluku Tengah"],
            ["id" => 260, "province_id" => 19, "city_name" => "Kabupaten Maluku Tenggara"],
            ["id" => 261, "province_id" => 19, "city_name" => "Kabupaten Maluku Tenggara Barat"],
            ["id" => 262, "province_id" => 27, "city_name" => "Kabupaten Mamasa"],
            ["id" => 263, "province_id" => 24, "city_name" => "Kabupaten Mamberamo Raya"],
            ["id" => 264, "province_id" => 24, "city_name" => "Kabupaten Mamberamo Tengah"],
            ["id" => 265, "province_id" => 27, "city_name" => "Kabupaten Mamuju"],
            ["id" => 266, "province_id" => 27, "city_name" => "Kabupaten Mamuju Utara"],
            ["id" => 267, "province_id" => 31, "city_name" => "Kota Manado"],
            ["id" => 268, "province_id" => 34, "city_name" => "Kabupaten Mandailing Natal"],
            ["id" => 269, "province_id" => 23, "city_name" => "Kabupaten Manggarai"],
            ["id" => 270, "province_id" => 23, "city_name" => "Kabupaten Manggarai Barat"],
            ["id" => 271, "province_id" => 23, "city_name" => "Kabupaten Manggarai Timur"],
            ["id" => 272, "province_id" => 25, "city_name" => "Kabupaten Manokwari"],
            ["id" => 273, "province_id" => 25, "city_name" => "Kabupaten Manokwari Selatan"],
            ["id" => 274, "province_id" => 24, "city_name" => "Kabupaten Mappi"],
            ["id" => 275, "province_id" => 28, "city_name" => "Kabupaten Maros"],
            ["id" => 276, "province_id" => 22, "city_name" => "Kota Mataram"],
            ["id" => 277, "province_id" => 25, "city_name" => "Kabupaten Maybrat"],
            ["id" => 278, "province_id" => 34, "city_name" => "Kota Medan"],
            ["id" => 279, "province_id" => 12, "city_name" => "Kabupaten Melawi"],
            ["id" => 280, "province_id" => 8, "city_name" => "Kabupaten Merangin"],
            ["id" => 281, "province_id" => 24, "city_name" => "Kabupaten Merauke"],
            ["id" => 282, "province_id" => 18, "city_name" => "Kabupaten Mesuji"],
            ["id" => 283, "province_id" => 18, "city_name" => "Kota Metro"],
            ["id" => 284, "province_id" => 24, "city_name" => "Kabupaten Mimika"],
            ["id" => 285, "province_id" => 31, "city_name" => "Kabupaten Minahasa"],
            ["id" => 286, "province_id" => 31, "city_name" => "Kabupaten Minahasa Selatan"],
            ["id" => 287, "province_id" => 31, "city_name" => "Kabupaten Minahasa Tenggara"],
            ["id" => 288, "province_id" => 31, "city_name" => "Kabupaten Minahasa Utara"],
            ["id" => 289, "province_id" => 11, "city_name" => "Kabupaten Mojokerto"],
            ["id" => 290, "province_id" => 11, "city_name" => "Kota Mojokerto"],
            ["id" => 291, "province_id" => 29, "city_name" => "Kabupaten Morowali"],
            ["id" => 292, "province_id" => 33, "city_name" => "Kabupaten Muara Enim"],
            ["id" => 293, "province_id" => 8, "city_name" => "Kabupaten Muaro Jambi"],
            ["id" => 294, "province_id" => 4, "city_name" => "Kabupaten Muko Muko"],
            ["id" => 295, "province_id" => 30, "city_name" => "Kabupaten Muna"],
            ["id" => 296, "province_id" => 14, "city_name" => "Kabupaten Murung Raya"],
            ["id" => 297, "province_id" => 33, "city_name" => "Kabupaten Musi Banyuasin"],
            ["id" => 298, "province_id" => 33, "city_name" => "Kabupaten Musi Rawas"],
            ["id" => 299, "province_id" => 24, "city_name" => "Kabupaten Nabire"],
            ["id" => 300, "province_id" => 21, "city_name" => "Kabupaten Nagan Raya"],
            ["id" => 301, "province_id" => 23, "city_name" => "Kabupaten Nagekeo"],
            ["id" => 302, "province_id" => 17, "city_name" => "Kabupaten Natuna"],
            ["id" => 303, "province_id" => 24, "city_name" => "Kabupaten Nduga"],
            ["id" => 304, "province_id" => 23, "city_name" => "Kabupaten Ngada"],
            ["id" => 305, "province_id" => 11, "city_name" => "Kabupaten Nganjuk"],
            ["id" => 306, "province_id" => 11, "city_name" => "Kabupaten Ngawi"],
            ["id" => 307, "province_id" => 34, "city_name" => "Kabupaten Nias"],
            ["id" => 308, "province_id" => 34, "city_name" => "Kabupaten Nias Barat"],
            ["id" => 309, "province_id" => 34, "city_name" => "Kabupaten Nias Selatan"],
            ["id" => 310, "province_id" => 34, "city_name" => "Kabupaten Nias Utara"],
            ["id" => 311, "province_id" => 16, "city_name" => "Kabupaten Nunukan"],
            ["id" => 312, "province_id" => 33, "city_name" => "Kabupaten Ogan Ilir"],
            ["id" => 313, "province_id" => 33, "city_name" => "Kabupaten Ogan Komering Ilir"],
            ["id" => 314, "province_id" => 33, "city_name" => "Kabupaten Ogan Komering Ulu"],
            ["id" => 315, "province_id" => 33, "city_name" => "Kabupaten Ogan Komering Ulu Selatan"],
            ["id" => 316, "province_id" => 33, "city_name" => "Kabupaten Ogan Komering Ulu Timur"],
            ["id" => 317, "province_id" => 11, "city_name" => "Kabupaten Pacitan"],
            ["id" => 318, "province_id" => 32, "city_name" => "Kota Padang"],
            ["id" => 319, "province_id" => 34, "city_name" => "Kabupaten Padang Lawas"],
            ["id" => 320, "province_id" => 34, "city_name" => "Kabupaten Padang Lawas Utara"],
            ["id" => 321, "province_id" => 32, "city_name" => "Kota Padang Panjang"],
            ["id" => 322, "province_id" => 32, "city_name" => "Kabupaten Padang Pariaman"],
            ["id" => 323, "province_id" => 34, "city_name" => "Kota Padang Sidempuan"],
            ["id" => 324, "province_id" => 33, "city_name" => "Kota Pagar Alam"],
            ["id" => 325, "province_id" => 34, "city_name" => "Kabupaten Pakpak Bharat"],
            ["id" => 326, "province_id" => 14, "city_name" => "Kota Palangka Raya"],
            ["id" => 327, "province_id" => 33, "city_name" => "Kota Palembang"],
            ["id" => 328, "province_id" => 28, "city_name" => "Kota Palopo"],
            ["id" => 329, "province_id" => 29, "city_name" => "Kota Palu"],
            ["id" => 330, "province_id" => 11, "city_name" => "Kabupaten Pamekasan"],
            ["id" => 331, "province_id" => 3, "city_name" => "Kabupaten Pandeglang"],
            ["id" => 332, "province_id" => 9, "city_name" => "Kabupaten Pangandaran"],
            ["id" => 333, "province_id" => 28, "city_name" => "Kabupaten Pangkajene Kepulauan"],
            ["id" => 334, "province_id" => 2, "city_name" => "Kota Pangkal Pinang"],
            ["id" => 335, "province_id" => 24, "city_name" => "Kabupaten Paniai"],
            ["id" => 336, "province_id" => 28, "city_name" => "Kota Parepare"],
            ["id" => 337, "province_id" => 32, "city_name" => "Kota Pariaman"],
            ["id" => 338, "province_id" => 29, "city_name" => "Kabupaten Parigi Moutong"],
            ["id" => 339, "province_id" => 32, "city_name" => "Kabupaten Pasaman"],
            ["id" => 340, "province_id" => 32, "city_name" => "Kabupaten Pasaman Barat"],
            ["id" => 341, "province_id" => 15, "city_name" => "Kabupaten Paser"],
            ["id" => 342, "province_id" => 11, "city_name" => "Kabupaten Pasuruan"],
            ["id" => 343, "province_id" => 11, "city_name" => "Kota Pasuruan"],
            ["id" => 344, "province_id" => 10, "city_name" => "Kabupaten Pati"],
            ["id" => 345, "province_id" => 32, "city_name" => "Kota Payakumbuh"],
            ["id" => 346, "province_id" => 25, "city_name" => "Kabupaten Pegunungan Arfak"],
            ["id" => 347, "province_id" => 24, "city_name" => "Kabupaten Pegunungan Bintang"],
            ["id" => 348, "province_id" => 10, "city_name" => "Kabupaten Pekalongan"],
            ["id" => 349, "province_id" => 10, "city_name" => "Kota Pekalongan"],
            ["id" => 350, "province_id" => 26, "city_name" => "Kota Pekanbaru"],
            ["id" => 351, "province_id" => 26, "city_name" => "Kabupaten Pelalawan"],
            ["id" => 352, "province_id" => 10, "city_name" => "Kabupaten Pemalang"],
            ["id" => 353, "province_id" => 34, "city_name" => "Kota Pematang Siantar"],
            ["id" => 354, "province_id" => 15, "city_name" => "Kabupaten Penajam Paser Utara"],
            ["id" => 355, "province_id" => 18, "city_name" => "Kabupaten Pesawaran"],
            ["id" => 356, "province_id" => 18, "city_name" => "Kabupaten Pesisir Barat"],
            ["id" => 357, "province_id" => 32, "city_name" => "Kabupaten Pesisir Selatan"],
            ["id" => 358, "province_id" => 21, "city_name" => "Kabupaten Pidie"],
            ["id" => 359, "province_id" => 21, "city_name" => "Kabupaten Pidie Jaya"],
            ["id" => 360, "province_id" => 28, "city_name" => "Kabupaten Pinrang"],
            ["id" => 361, "province_id" => 7, "city_name" => "Kabupaten Pohuwato"],
            ["id" => 362, "province_id" => 27, "city_name" => "Kabupaten Polewali Mandar"],
            ["id" => 363, "province_id" => 11, "city_name" => "Kabupaten Ponorogo"],
            ["id" => 364, "province_id" => 12, "city_name" => "Kabupaten Pontianak"],
            ["id" => 365, "province_id" => 12, "city_name" => "Kota Pontianak"],
            ["id" => 366, "province_id" => 29, "city_name" => "Kabupaten Poso"],
            ["id" => 367, "province_id" => 33, "city_name" => "Kota Prabumulih"],
            ["id" => 368, "province_id" => 18, "city_name" => "Kabupaten Pringsewu"],
            ["id" => 369, "province_id" => 11, "city_name" => "Kabupaten Probolinggo"],
            ["id" => 370, "province_id" => 11, "city_name" => "Kota Probolinggo"],
            ["id" => 371, "province_id" => 14, "city_name" => "Kabupaten Pulang Pisau"],
            ["id" => 372, "province_id" => 20, "city_name" => "Kabupaten Pulau Morotai"],
            ["id" => 373, "province_id" => 24, "city_name" => "Kabupaten Puncak"],
            ["id" => 374, "province_id" => 24, "city_name" => "Kabupaten Puncak Jaya"],
            ["id" => 375, "province_id" => 10, "city_name" => "Kabupaten Purbalingga"],
            ["id" => 376, "province_id" => 9, "city_name" => "Kabupaten Purwakarta"],
            ["id" => 377, "province_id" => 10, "city_name" => "Kabupaten Purworejo"],
            ["id" => 378, "province_id" => 25, "city_name" => "Kabupaten Raja Ampat"],
            ["id" => 379, "province_id" => 4, "city_name" => "Kabupaten Rejang Lebong"],
            ["id" => 380, "province_id" => 10, "city_name" => "Kabupaten Rembang"],
            ["id" => 381, "province_id" => 26, "city_name" => "Kabupaten Rokan Hilir"],
            ["id" => 382, "province_id" => 26, "city_name" => "Kabupaten Rokan Hulu"],
            ["id" => 383, "province_id" => 23, "city_name" => "Kabupaten Rote Ndao"],
            ["id" => 384, "province_id" => 21, "city_name" => "Kota Sabang"],
            ["id" => 385, "province_id" => 23, "city_name" => "Kabupaten Sabu Raijua"],
            ["id" => 386, "province_id" => 10, "city_name" => "Kota Salatiga"],
            ["id" => 387, "province_id" => 15, "city_name" => "Kota Samarinda"],
            ["id" => 388, "province_id" => 12, "city_name" => "Kabupaten Sambas"],
            ["id" => 389, "province_id" => 34, "city_name" => "Kabupaten Samosir"],
            ["id" => 390, "province_id" => 11, "city_name" => "Kabupaten Sampang"],
            ["id" => 391, "province_id" => 12, "city_name" => "Kabupaten Sanggau"],
            ["id" => 392, "province_id" => 24, "city_name" => "Kabupaten Sarmi"],
            ["id" => 393, "province_id" => 8, "city_name" => "Kabupaten Sarolangun"],
            ["id" => 394, "province_id" => 32, "city_name" => "Kota Sawah Lunto"],
            ["id" => 395, "province_id" => 12, "city_name" => "Kabupaten Sekadau"],
            ["id" => 396, "province_id" => 28, "city_name" => "Kabupaten Selayar (Kepulauan Selayar)"],
            ["id" => 397, "province_id" => 4, "city_name" => "Kabupaten Seluma"],
            ["id" => 398, "province_id" => 10, "city_name" => "Kabupaten Semarang"],
            ["id" => 399, "province_id" => 10, "city_name" => "Kota Semarang"],
            ["id" => 400, "province_id" => 19, "city_name" => "Kabupaten Seram Bagian Barat"],
            ["id" => 401, "province_id" => 19, "city_name" => "Kabupaten Seram Bagian Timur"],
            ["id" => 402, "province_id" => 3, "city_name" => "Kabupaten Serang"],
            ["id" => 403, "province_id" => 3, "city_name" => "Kota Serang"],
            ["id" => 404, "province_id" => 34, "city_name" => "Kabupaten Serdang Bedagai"],
            ["id" => 405, "province_id" => 14, "city_name" => "Kabupaten Seruyan"],
            ["id" => 406, "province_id" => 26, "city_name" => "Kabupaten Siak"],
            ["id" => 407, "province_id" => 34, "city_name" => "Kota Sibolga"],
            ["id" => 408, "province_id" => 28, "city_name" => "Kabupaten Sidenreng Rappang/Rapang"],
            ["id" => 409, "province_id" => 11, "city_name" => "Kabupaten Sidoarjo"],
            ["id" => 410, "province_id" => 29, "city_name" => "Kabupaten Sigi"],
            ["id" => 411, "province_id" => 32, "city_name" => "Kabupaten Sijunjung (Sawah Lunto Sijunjung)"],
            ["id" => 412, "province_id" => 23, "city_name" => "Kabupaten Sikka"],
            ["id" => 413, "province_id" => 34, "city_name" => "Kabupaten Simalungun"],
            ["id" => 414, "province_id" => 21, "city_name" => "Kabupaten Simeulue"],
            ["id" => 415, "province_id" => 12, "city_name" => "Kota Singkawang"],
            ["id" => 416, "province_id" => 28, "city_name" => "Kabupaten Sinjai"],
            ["id" => 417, "province_id" => 12, "city_name" => "Kabupaten Sintang"],
            ["id" => 418, "province_id" => 11, "city_name" => "Kabupaten Situbondo"],
            ["id" => 419, "province_id" => 5, "city_name" => "Kabupaten Sleman"],
            ["id" => 420, "province_id" => 32, "city_name" => "Kabupaten Solok"],
            ["id" => 421, "province_id" => 32, "city_name" => "Kota Solok"],
            ["id" => 422, "province_id" => 32, "city_name" => "Kabupaten Solok Selatan"],
            ["id" => 423, "province_id" => 28, "city_name" => "Kabupaten Soppeng"],
            ["id" => 424, "province_id" => 25, "city_name" => "Kabupaten Sorong"],
            ["id" => 425, "province_id" => 25, "city_name" => "Kota Sorong"],
            ["id" => 426, "province_id" => 25, "city_name" => "Kabupaten Sorong Selatan"],
            ["id" => 427, "province_id" => 10, "city_name" => "Kabupaten Sragen"],
            ["id" => 428, "province_id" => 9, "city_name" => "Kabupaten Subang"],
            ["id" => 429, "province_id" => 21, "city_name" => "Kota Subulussalam"],
            ["id" => 430, "province_id" => 9, "city_name" => "Kabupaten Sukabumi"],
            ["id" => 431, "province_id" => 9, "city_name" => "Kota Sukabumi"],
            ["id" => 432, "province_id" => 14, "city_name" => "Kabupaten Sukamara"],
            ["id" => 433, "province_id" => 10, "city_name" => "Kabupaten Sukoharjo"],
            ["id" => 434, "province_id" => 23, "city_name" => "Kabupaten Sumba Barat"],
            ["id" => 435, "province_id" => 23, "city_name" => "Kabupaten Sumba Barat Daya"],
            ["id" => 436, "province_id" => 23, "city_name" => "Kabupaten Sumba Tengah"],
            ["id" => 437, "province_id" => 23, "city_name" => "Kabupaten Sumba Timur"],
            ["id" => 438, "province_id" => 22, "city_name" => "Kabupaten Sumbawa"],
            ["id" => 439, "province_id" => 22, "city_name" => "Kabupaten Sumbawa Barat"],
            ["id" => 440, "province_id" => 9, "city_name" => "Kabupaten Sumedang"],
            ["id" => 441, "province_id" => 11, "city_name" => "Kabupaten Sumenep"],
            ["id" => 442, "province_id" => 8, "city_name" => "Kota Sungaipenuh"],
            ["id" => 443, "province_id" => 24, "city_name" => "Kabupaten Supiori"],
            ["id" => 444, "province_id" => 11, "city_name" => "Kota Surabaya"],
            ["id" => 445, "province_id" => 10, "city_name" => "Kota Surakarta (Solo)"],
            ["id" => 446, "province_id" => 13, "city_name" => "Kabupaten Tabalong"],
            ["id" => 447, "province_id" => 1, "city_name" => "Kabupaten Tabanan"],
            ["id" => 448, "province_id" => 28, "city_name" => "Kabupaten Takalar"],
            ["id" => 449, "province_id" => 25, "city_name" => "Kabupaten Tambrauw"],
            ["id" => 450, "province_id" => 16, "city_name" => "Kabupaten Tana Tidung"],
            ["id" => 451, "province_id" => 28, "city_name" => "Kabupaten Tana Toraja"],
            ["id" => 452, "province_id" => 13, "city_name" => "Kabupaten Tanah Bumbu"],
            ["id" => 453, "province_id" => 32, "city_name" => "Kabupaten Tanah Datar"],
            ["id" => 454, "province_id" => 13, "city_name" => "Kabupaten Tanah Laut"],
            ["id" => 455, "province_id" => 3, "city_name" => "Kabupaten Tangerang"],
            ["id" => 456, "province_id" => 3, "city_name" => "Kota Tangerang"],
            ["id" => 457, "province_id" => 3, "city_name" => "Kota Tangerang Selatan"],
            ["id" => 458, "province_id" => 18, "city_name" => "Kabupaten Tanggamus"],
            ["id" => 459, "province_id" => 34, "city_name" => "Kota Tanjung Balai"],
            ["id" => 460, "province_id" => 8, "city_name" => "Kabupaten Tanjung Jabung Barat"],
            ["id" => 461, "province_id" => 8, "city_name" => "Kabupaten Tanjung Jabung Timur"],
            ["id" => 462, "province_id" => 17, "city_name" => "Kota Tanjung Pinang"],
            ["id" => 463, "province_id" => 34, "city_name" => "Kabupaten Tapanuli Selatan"],
            ["id" => 464, "province_id" => 34, "city_name" => "Kabupaten Tapanuli Tengah"],
            ["id" => 465, "province_id" => 34, "city_name" => "Kabupaten Tapanuli Utara"],
            ["id" => 466, "province_id" => 13, "city_name" => "Kabupaten Tapin"],
            ["id" => 467, "province_id" => 16, "city_name" => "Kota Tarakan"],
            ["id" => 468, "province_id" => 9, "city_name" => "Kabupaten Tasikmalaya"],
            ["id" => 469, "province_id" => 9, "city_name" => "Kota Tasikmalaya"],
            ["id" => 470, "province_id" => 34, "city_name" => "Kota Tebing Tinggi"],
            ["id" => 471, "province_id" => 8, "city_name" => "Kabupaten Tebo"],
            ["id" => 472, "province_id" => 10, "city_name" => "Kabupaten Tegal"],
            ["id" => 473, "province_id" => 10, "city_name" => "Kota Tegal"],
            ["id" => 474, "province_id" => 25, "city_name" => "Kabupaten Teluk Bintuni"],
            ["id" => 475, "province_id" => 25, "city_name" => "Kabupaten Teluk Wondama"],
            ["id" => 476, "province_id" => 10, "city_name" => "Kabupaten Temanggung"],
            ["id" => 477, "province_id" => 20, "city_name" => "Kota Ternate"],
            ["id" => 478, "province_id" => 20, "city_name" => "Kota Tidore Kepulauan"],
            ["id" => 479, "province_id" => 23, "city_name" => "Kabupaten Timor Tengah Selatan"],
            ["id" => 480, "province_id" => 23, "city_name" => "Kabupaten Timor Tengah Utara"],
            ["id" => 481, "province_id" => 34, "city_name" => "Kabupaten Toba Samosir"],
            ["id" => 482, "province_id" => 29, "city_name" => "Kabupaten Tojo Una-Una"],
            ["id" => 483, "province_id" => 29, "city_name" => "Kabupaten Toli-Toli"],
            ["id" => 484, "province_id" => 24, "city_name" => "Kabupaten Tolikara"],
            ["id" => 485, "province_id" => 31, "city_name" => "Kota Tomohon"],
            ["id" => 486, "province_id" => 28, "city_name" => "Kabupaten Toraja Utara"],
            ["id" => 487, "province_id" => 11, "city_name" => "Kabupaten Trenggalek"],
            ["id" => 488, "province_id" => 19, "city_name" => "Kota Tual"],
            ["id" => 489, "province_id" => 11, "city_name" => "Kabupaten Tuban"],
            ["id" => 490, "province_id" => 18, "city_name" => "Kabupaten Tulang Bawang"],
            ["id" => 491, "province_id" => 18, "city_name" => "Kabupaten Tulang Bawang Barat"],
            ["id" => 492, "province_id" => 11, "city_name" => "Kabupaten Tulungagung"],
            ["id" => 493, "province_id" => 28, "city_name" => "Kabupaten Wajo"],
            ["id" => 494, "province_id" => 30, "city_name" => "Kabupaten Wakatobi"],
            ["id" => 495, "province_id" => 24, "city_name" => "Kabupaten Waropen"],
            ["id" => 496, "province_id" => 18, "city_name" => "Kabupaten Way Kanan"],
            ["id" => 497, "province_id" => 10, "city_name" => "Kabupaten Wonogiri"],
            ["id" => 498, "province_id" => 10, "city_name" => "Kabupaten Wonosobo"],
            ["id" => 499, "province_id" => 24, "city_name" => "Kabupaten Yahukimo"],
            ["id" => 500, "province_id" => 24, "city_name" => "Kabupaten Yalimo"],
            ["id" => 501, "province_id" => 5, "city_name" => "Kota Yogyakarta"],
        ];
        foreach ($cities as $data) {
            City::create([
                'id'=>$data['id'],
                'province_id'=>$data['province_id'],
                'city_name'=>$data['city_name'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
